# Generated by Django 3.1.4 on 2020-12-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('editor', 'Editor User'), ('reviewer', 'Reviewer User'), ('auditor', 'Auditor User')),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
