# Generated by Django 3.1.4 on 2020-12-25 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userssupport',
            options={'default_permissions': (), 'managed': False, 'permissions': (('editor', 'Editor User'), ('reviewer', 'Reviewer User'), ('internal', 'Internal User'))},
        ),
    ]
